import type { Metadata } from "next";
import { getHeader, getFooter } from "@/lib/contentstack";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [header, footer] = await Promise.all([
    getHeader(),
    getFooter()
  ]);

  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        {header && <Header header={header} />}
        <main className="flex-grow">
          {children}
        </main>
        {footer && <Footer footer={footer} />}
      </body>
    </html>
  );
}